name: Deploy Central Print Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no printingserver@104.218.48.99 << 'EOF'
            cd ~/central-print-server
            git reset --hard
            git pull origin main
            pm2 restart printserver || pm2 start server.js --name printserver
          EOF
