name: Deploy Central Print Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup SSH key
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      # Step 3: Deploy to VPS
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no printingserver@104.218.48.99 << 'EOF'
            echo "✅ Connected to VPS"

            # Ensure Node.js is installed (v22.x)
            if ! command -v node >/dev/null 2>&1; then
              curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            # Navigate to the app directory
            cd ~/central-print-server

            # Reset local changes and pull latest code
            git reset --hard
            git pull origin main

            # Install/update dependencies
            npm install

            # Restart or start the server via PM2
            pm2 restart printserver || pm2 start server.js --name printserver

            # Save PM2 process list and enable startup
            pm2 save
            pm2 startup systemd -u printingserver --hp /home/printingserver

            echo "✅ Deployment complete"
          EOF
